### PR TITLE
docs: extend content of about message

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
This PR extends the content of the `About` with:
- the copyright associated to `PySide6`;
- a link to the LPGL v3.0 for the combined work with `PySide6`, aka the GUI.

### CODE REVIEW

**Review by RobPasMue — APPROVED** [review]
LGTM!

**Comment by RobPasMue** [comment]
Hmm seems like the doc build is failing

**Comment by SMoraisAnsys** [comment]
Seems unrelated to the changes though 

image

**Comment by RobPasMue** [comment]
Must have been temporary - merging since all passed

**Pull request merged**
