### PR TITLE
fix: Windows DLL load issues related to PyInstaller

### LINKED ISSUE #376: Pyinstaller's use of SetDllDirectory can interfere with DLL loading in applications launched from Python Manager
The Windows API [provides a function](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectoryw) called `SetDllDirectory` that allows a process to override the typical search order for DLLs. Calls to this function will impact any future launched child processes. The influence over the DLL search path is not accomplished by altering the `PATH` environment variable, so it can be difficult to determine when this has happened.

`pyinstaller` [uses this function in frozen applications](https://github.com/pyinstaller/pyinstaller/issues/3795#issuecomment-431158007) in order to provide support for custom ctypes DLLs in "onefile" deployments. Specifically, it adds the app's `_internal` directory to the DLL search path. The current version of the Python Manager ships a number of DLLs in this directory. When a user uses the Python Manager to launch a command prompt into a `venv`, this change to the DLL search order is inherited by that command prompt, and then by any Python interpreter launched within that command prompt.

Practically speaking, this prevents applications which might depend on a different version of some of these DLLs from finding them, even if they would otherwise be able to. For example, when attempting to load a ModelCenter workflow containing an embedded DOE via pyModelCenter, if this attempt is made from a command prompt launched by the Python Manager, the DOE tool is unable to load the oSL DOE algorithms. It seems likely to me that this is also the root cause of bug #375. In the ModelCenter use case, the specific problem is the presence of a copy of `libcrypto-3-x64`. As an aside, this DLL doesn't seem to be actually used by the Python Manager -- removing it did not seem to have any impact on the usability of the program, and happened to allow loading of those workflows in this specific case.

This is a ["known issue" with `pyinstaller`](https://github.com/pyinstaller/pyinstaller/issues/3795). The `pyinstaller` wiki [contains a suggested workaround](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess#windows-dll-loading-order), which is essentially to call that same Windows API function in such a manner that the changes to the search path are undone. Because of the intended use of the Ansys Python Manager (i.e. to be a convenient way to manage Python installations and .venvs), I think we should consider either applying his workaround to the Python Manager, or modifying it such that it launches command prompts for .venvs in such a way that they do not inherit this change to the DLL search path.

### Workarounds

1. Because Ansys Python manager creates regular venvs in a location accessible to the user, launching a command prompt directly and activating the venv yourself manually sidesteps the issue; the problem is only introduced when Ansys Python Manager launches a command prompt for you, not when Python is installed / the venv is created / packages are installed in the venv.
2. The [aforementioned workaround](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess#windows-dll-loading-order) suggested by the `pyinstaller` wiki can also be applied by a Python script which is about to launch a native application which would be affected by this. I was able to test this for the specific ModelCenter use case mentioned above. It's worth noting that the general principle behind the workaround (calling `SetDllDirectory` with a `NULL` argument) could be applied by any code with access to the Windows API which has a chance to execute before the affected attempt to load a DLL that exists in the Python Manager's installation directory.

### PR DESCRIPTION
**Pull request by RobPasMue**
Closes #376

### CODE REVIEW

**Comment by RobPasMue** [comment]
@phx-mkoninckx could you give it a try to the executable that gets generated from the workflow? We are resetting the DLL loading as suggested in the PyInstaller documentation now. Also took the opportunity to revert the hack we implemented for the paths.

**Comment by RobPasMue** [comment]
(Linux failing build is expected and under investigation by @tusharbana-ansys)

**Comment by phx-mkoninckx** [comment]
@RobPasMue 

This _does_ seem to resolve the specific issue I was looking at when I reported #376. However, I'm concerned about the revert of #344. The fix in #344 did actually have some impact; without it, `PATH` includes the `_internal` and `_internal\PySide6` subdirectories from the directory where the Ansys Python Manager exists on disk:

```
(bug_repro) C:\Users\Admin>echo %PATH%
C:\Users\Admin\.ansys_python_venvs\bug_repro\Scripts;C:\Users\Admin\python-installer-qt-gui\dist\ansys_python_manager\_internal\PySide6;C:\Users\Admin\python-installer-qt-gui\dist\ansys_python_manager\_internal;C:\Program Files\Microsoft\jdk-11.0.18.10-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Admin\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Admin\AppData\Local\Programs\Python\Python311\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;
```
Overall, this is less concerning than the impact of calling `SetDllDirectory`, since:
1. Generally, DLLs are located by searching the `PATH` as a last-ditch effort. This means that these alterations to the `PATH` are, practically, somewhat less likely to impact most applications, since most native Windows apps don't depend on finding their DLLs on the `PATH` and instead expect to find them in the same directory as the application. Or, if they do depend on the `PATH` to load certain DLLs, they are probably putting their expected locations on the `PATH` first before attempting such a load. (This is the case for ModelCenter -- the DOE plug-in is run out-of-process, and when ModelCenter Desktop launches the DOE plug-in, it adds a centralized installation directory for the oSL algorithms to the subprocess' `PATH`).
2. When attempting to debug issues caused by alterations to the `PATH`, it's somewhat easier to tell what's going on and deal with it.

However, if #344 was really the fix for #343, then reverting it could cause #343 to regress?

**Comment by RobPasMue** [comment]
Good point @phx-mkoninckx - I just checked it with the dev version and saw it was no longer in the PATH, buuut... that is not true if you used the full solution (executable on workflow). Reapplying the change. Thanks a lot for all the explanations @phx-mkoninckx!!

**Review by phx-mkoninckx — APPROVED** [review]
Awesome, thanks! @RobPasMue -- with respect to the changes to `PATH`, I start to wonder if what might be better than trying to undo the addition of the `_internal` directory would either be to:

a) attempt to read and use the registry key that Windows would use to set the environment of a newly-started command prompt
b) look into ways to launch processes from Python such that they don't inherit the environment from the Python interpreter process but instead emulate the behavior of them being launched by the user from the Windows shell (i.e. `explorer.exe`; the initial environment is based on the Control Panel settings for environment variables). But that would be a separate PR / issue

**Pull request merged**
