### PR TITLE
Uninstaller script and configure virtual environment create & search path.  

### PR DESCRIPTION
**Pull request by anssakthi**
Pull request for the implementation of configuration window to configure path and Linux distro uninstaller script. 

## Description
This Pull request is to provide option for the user to alter virtual environment create and search path in addition to that implemented menu option to uninstall Ansys python manager on Linux distribution. 

## Related Issue
[#80 ](https://github.com/ansys/python-installer-qt-gui/issues/80)

### CODE REVIEW

**Comment by RobPasMue** [comment]
Hi @anssakthi @tusharbana-ansys - I'll try to start reviewing today but I'm still travelling in Pune so it might take me some time

**Comment by RobPasMue** [comment]
I think the best way for me to check this PR is to actually clone the branch and try it out manually on Windows. I'll do the same on Linux.

**Comment by anssakthi** [comment]
> I think the best way for me to check this PR is to actually clone the branch and try it out manually on Windows. I'll do the same on Linux.

@RobPasMue Downloaded the windows signed artifact from [here](https://github.com/ansys/python-installer-qt-gui/actions/runs/8262939792) and verified the configuration window.

**Review by RobPasMue — APPROVED** [review]
Overall LGTM! Thank you both for the implementation! I think we should do a release after this... do you agree?

**Comment by anssakthi** [comment]
Thanks @RobPasMue. Let's release the change.

**Pull request merged**
