### PR TITLE
feat: adding kmahajan-cadfem as contributor + missing metadata

### PR DESCRIPTION
**Pull request by RobPasMue**
As title says. Thanks @kmahajan-cadfem for all your contributions!

### CODE REVIEW

**Comment by RobPasMue** [comment]
FYI... could you try out this exe on your side? It should contain your changes from #116 

https://github.com/ansys/python-installer-qt-gui/suites/13538111796/artifacts/744585296

**Comment by RobPasMue** [comment]
Looks like I am having some problems on my side when running it. I'll try fixing them.

image

**Review by kmahajan-cadfem — APPROVED** [review]
Thanks @RobPasMue 😊

**Comment by kmahajan-cadfem** [comment]
> FYI... could you try out this exe on your side? It should contain your changes from #116
> 
> https://github.com/ansys/python-installer-qt-gui/suites/13538111796/artifacts/744585296

Have same error message now, maybe something missing in ansys-tools-path package?

**Comment by kmahajan-cadfem** [comment]
@RobPasMue,
I think following is the solution

https://github.com/pyinstaller/pyinstaller/issues/5878#issuecomment-1130150692

have to change [frozen.spec](frozen.spec)

**Comment by RobPasMue** [comment]
> @RobPasMue, I think following is the solution
> 
> [pyinstaller/pyinstaller#5878 (comment)](https://github.com/pyinstaller/pyinstaller/issues/5878#issuecomment-1130150692)
> 
> have to change [frozen.spec](frozen.spec)

That's right. I think I arrived to the same conclusion. Let me try and add that.

**Comment by RobPasMue** [comment]
Tried it locally. Seems to work. I will wait for the artifacts from GH Actions to test it. Afterwards, I will do a new patch release of the Ansys Python Manager 😄 - thanks @kmahajan-cadfem!

**Comment by RobPasMue** [comment]
See https://github.com/ansys/python-installer-qt-gui/suites/13539036986/artifacts/744645763

**Comment by RobPasMue** [comment]
Everything worked fine. Release triggered. 0.2.3 coming up

**Pull request merged**
